name: neom_commerce
description: Commerce Details for Cyberneom.
version: 1.3.1
homepage: https://github.com/emmanuel-montoya/neom_commerce
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  neom_commons:
    git:
      url: git@github.com:Cyberneom/neom_commons.git
  neom_bands:
    git:
      url: git@github.com:emmanuel-montoya/neom_bands.git
  neom_posts:
    git:
      url: git@github.com:Cyberneom/neom_posts.git

  flutter_stripe: ^11.5.0
  in_app_purchase: ^3.2.3
  in_app_purchase_storekit: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
